import Head from "next/head";
import { useRouter } from "next/router";
import { Button } from "react-bootstrap";


export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title> Home </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p> This is Home </p>
        <div className="d-flex justify-items-center align-items-center">
          <Button className="btn btn-dark" onClick={()=>{ router.push("/signup")}}>
             Signup
          </Button>
        </div>
      </main>
    </>
  );
}
